name: Pull Request

on: pull_request

env:
  DOTNET_NOLOGO: true
  LOWEST_FRAMEWORK: net8.0
  HIGHEST_FRAMEWORK: net10.0

jobs:

  build_and_test_debug:
    name: Build and test with CodeCov (DEBUG)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Cache NuGet packages
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - run: dotnet restore --verbosity minimal

      - run: dotnet build --configuration Debug /p:ContinuousIntegrationBuild=true

      - name: Run tests with code coverage
        run: dotnet run --project ./src/SimpleAWS.S3.Downloader.Core.Tests/SimpleAWS.S3.Downloader.Core.Tests.csproj --configuration Debug --no-build --framework ${{ env.HIGHEST_FRAMEWORK }} -- --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml

      - name: Code coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./src/SimpleAWS.S3.Downloader.Core.Tests/**/coverage.cobertura.xml
          fail_ci_if_error: true

  build_and_test_release:
    name: Build and test (RELEASE)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build version prefix/suffix
        run: |
          echo "VERSION_PREFIX=$(( ${{ github.run_number }} )).0.0" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=alpha" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Cache NuGet packages
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - run: dotnet restore --verbosity minimal

      - run: dotnet build --configuration Release -p:ContinuousIntegrationBuild=true -p:DebugType=Embedded -p:VersionPrefix=$VERSION_PREFIX --version-suffix $VERSION_SUFFIX

      - name: Run tests
        run: dotnet run --project ./src/SimpleAWS.S3.Downloader.Core.Tests/SimpleAWS.S3.Downloader.Core.Tests.csproj --configuration Release --no-build
