name: Publish release assets

on:
  push:
    tags:
      - "*.*.*"
    paths-ignore:
      - '.editorconfig'
      - 'ReadMe.md'
      - 'ChangeLog.md'
      - '.github/workflows/PullRequest.yml'
      - '.github/workflows/MergeToMain.yml'

permissions:
  contents: write

env:
  DOTNET_NOLOGO: true

jobs:
  build_and_publish_release:
    name: Build and publish release executables
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [win-x64, linux-x64, osx-x64]
        variant: [selfcontained, framework]
        include:
          - variant: selfcontained
            selfContained: true
            includeAllContent: true
          - variant: framework
            selfContained: false
            includeAllContent: false

    steps:

      - name: Calculate version from the Commit Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Cache NuGet packages
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - run: dotnet restore --verbosity minimal

      - name: Publish single-file executable (${{ matrix.runtime }}-${{ matrix.variant }})
        run: dotnet publish ./src/SimpleAWS.S3.Downloader.Console/SimpleAWS.S3.Downloader.Console.csproj --configuration Release --runtime ${{ matrix.runtime }} --self-contained ${{ matrix.selfContained }} -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=${{ matrix.includeAllContent }} -p:ContinuousIntegrationBuild=true -p:DebugType=Embedded -p:Version=${{ env.RELEASE_VERSION }} --output ./artifacts/${{ matrix.runtime }}/${{ matrix.variant }}

      - name: Rename release executable (${{ matrix.runtime }}-${{ matrix.variant }})
        run: |
          if [ "${{ matrix.runtime }}" = "win-x64" ]; then
            mv "./artifacts/${{ matrix.runtime }}/${{ matrix.variant }}/SimpleAWS.S3.Downloader.Console.exe" "./artifacts/${{ matrix.runtime }}/${{ matrix.variant }}/SimpleAWS.S3.Downloader.Console-${{ matrix.runtime }}-${{ matrix.variant }}.exe"
          else
            mv "./artifacts/${{ matrix.runtime }}/${{ matrix.variant }}/SimpleAWS.S3.Downloader.Console" "./artifacts/${{ matrix.runtime }}/${{ matrix.variant }}/SimpleAWS.S3.Downloader.Console-${{ matrix.runtime }}-${{ matrix.variant }}"
          fi

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./artifacts/${{ matrix.runtime }}/${{ matrix.variant }}/SimpleAWS.S3.Downloader.Console-${{ matrix.runtime }}-${{ matrix.variant }}*
